### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by VarmaHub** [dice-group/FOX#38]
Hello,

I tried running the Docker file in **IntelliJ IDE** and it stops with an **error** stating; 
```
Dockerfile: docker/en/Dockerfile': 

 The command '/bin/sh -c ./downloadAgdistis.sh' returned a non-zero code: 127
```

![fox _ docker _ agdistis error](https://user-images.githubusercontent.com/17321286/34921679-f7d30274-f985-11e7-9a6f-ae56cc0d7b59.JPG)

**Comment by renespeck** [comment]
Hi, the error message says that the file './downloadAgdistis.sh' is not found. 

But the file should be there because it was copied before. Compare with that line: https://github.com/dice-group/FOX/blob/a7cf9ced75fac3095bf9bcfaa31c93a1b4179d31/docker/en/Dockerfile#L34

What I see is that your are in the folder '/bin/sh'. But should be '/usr/bin/FOX' compare with: https://github.com/dice-group/FOX/blob/a7cf9ced75fac3095bf9bcfaa31c93a1b4179d31/docker/en/Dockerfile#L23

Did you tried to run docker as described in the documentation (https://github.com/dice-group/FOX/blob/master/documentation/docker.md)? 
Do you get an error?

**Comment by VarmaHub** [comment]
After some workaround, been able to fix the stated error by converting line endings of _downloadAgdistis.sh_ file from **CRLF** to **LF**. 

![download agdistis](https://user-images.githubusercontent.com/17321286/34925606-a9f4da08-f9aa-11e7-850f-10422d960dfc.JPG)

Reference: [https://help.github.com/articles/dealing-with-line-endings/](url)

**Comment by renespeck** [comment]
Opened a new issue in #43.
