### ISSUE TITLE
Question: Import a Knowledge Base for Entity Extraction

### ISSUE THREAD

**Issue by ali1k** [dice-group/FOX#53]
Is it possible to use our custom knowledge graphs/ontologies/thesaurus  within the FOX? If yes, is there any documentations available about that?

**Comment by renespeck** [comment]
Hi, thanks for the question.  
The linking comes with the help of the AGDISTIS/MAG web service. 
To integrate another KG you need to integrate it in the AGDISTIS/MAG web service and update the endpoint of the service in the FOX config files. 

I hope that helps.

**Comment by ali1k** [comment]
Thanks for the answer. I get that for linking and disambiguation you use AGDISTIS. However, I was mainly thinking about custom word embeddings provided by a knowledge base other than DBpedia.

**Comment by DiegoMoussallem** [comment]
@ali1k can you explain it a bit more how to custom word embeddings? for example, you can use AGDISTIS/MAG with Wikidata and other KGs.

**Comment by ali1k** [comment]
What I mean is to spot entities based on indexes coming from a certain knowledge graph. I am looking for a custom NER tool that that can be adapted to different domains.

**Comment by vdanielupb** [comment]
@ali1k To learn a model for entity extraction with Rasa NLU you can use the following steps:
1. Generate a training file as described here: [https://rasa.com/docs/nlu/dataformat/](url)
2. Write a configuration file for Rasa NLU [https://rasa.com/docs/nlu/components/](url), so that it learns a CRF for entity extraction.
3. Use the Python API [https://rasa.com/docs/nlu/python/](url) of Rasa NLU to train the model

**Comment by ali1k** [comment]
@vdanielupb thanks, that is already very helpful.
